language: java
before_script:
  - echo "before script"
  - env

environments:
   - [lrc-slave, OracleJDK6]
   - [gva-slave, OracleJDK6]
   - [lrc-slave, OracleJDK7]
   - [gva-slave, OracleJDK7]
   - [lrc-slave, OracleJDK8]
   - [gva-slave, OracleJDK8]

jdk:
  - OracleJDK6
  - OracleJDK7
  - OracleJDK8

env:
  global:
    - JAVA_OPTS="-Xms64m"
  matrix:
    - SQ_VERSION='5.1'
    - SQ_VERSION='5.2'
    - SQ_VERSION='5.3'

build:
    lrc-slave:
      OracleJDK6: ./cix.sh
      OracleJDK7: ./cix.sh
      OracleJDK8: ./cix.sh
    gva-slave:
      OracleJDK6: ./cix.sh
      OracleJDK7: ./cix.sh
      OracleJDK8: ./cix.sh

