language: java
before_script:
  - echo "before script"
  - env

jdk:
  - OracleJDK6
  - OracleJDK7
  - OracleJDK8

env:
  global:
    - JAVA_OPTS="-Xms64m"
  matrix:
    - TARGET='123'
    - TARGET='456'
    - TARGET='789'

script: "java -version -Dmyval=$TARGET"
install: /bin/true
